secrets:
  - name:
    refreshInterval:
    secretStoreRef:
      kind:
      name:
    target:
      name:
    data:
    - secretKey:
      remoteRef:
        key:
  - name:
    refreshInterval:
    type:
    secretStoreRef:
      kind:
      name:
    target:
      name:
    data:
    - secretKey:
      remoteRef:
        key:
        property:
    - secretKey:
      remoteRef:
        key:
        property:

deployment:
  annotations:
  image:
  tag:
  replicaCount:
  port:
  restartPolicy:
  serviceAccountName:
  env:
  - name:
    value:
  - name:
    value:
  volumeMounts:
  - name:
    mountPath:
    subPath:
  volumes:
  - name:
    secret:
      secretName:

service:
  annotations:
  name:
  labels:
  type:
  ports:
  - protocol:
    port:

ingress:
- hostName:
  tls:
    enabled:
    redirect:
    type:
    secretName:
  paths:
    - 


