{{- if .Values.deployment }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.serviceName }}
  namespace: {{ .Values.namespace | lower }}
  labels:
    app: {{ .Values.serviceName }}
    {{- if .Values.deployment.annotations }}
  annotations:
    {{- toYaml .Values.deployment.annotations | nindent 4 }}
    {{- end }}
spec:
  replicas: {{ .Values.replicaCount | default  "1" }}
  selector:
    matchLabels:
      app: {{ .Values.serviceName }}
  template:
    metadata:
      labels:
        app: {{ .Values.serviceName }}
    spec:
      {{- if .Values.deployment.tolerations }}
      tolerations:
      {{- range $value := .Values.deployment.tolerations }}
      - key: {{ $value.key }}
        operator: {{ $value.operator }}
        value: {{ $value.value }}
        effect: {{ $value.effect }}
      {{- end }}
      {{- end }}
      {{- if .Values.deployment.nodeSelector }}
      nodeSelector:
        type: {{ .Values.deployment.nodeSelector.type }}
      {{- end }}
      containers:
      - image: {{ .Values.deployment.image }}:{{ .Values.deployment.tag }}
        imagePullPolicy: {{ .Values.deployment.pullPolicy | default  "Always"}}
        name: {{ .Values.serviceName }}
        {{- if .Values.deployment.command }}
        command: {{ .Values.deployment.command }}
        {{- end }}
        {{- if .Values.deployment.args }}
        args: {{ .Values.deployment.args }}
        {{- end }}
        {{- if .Values.deployment.startupProbe }}
        startupProbe:
          exec:
            command:
            {{- range $value := .Values.deployment.startupProbe.exec.command }}
            - {{ $value }}
            {{- end }}
          initialDelaySeconds: 30
        {{- end }}
        {{- if .Values.deployment.readinessProbe }}
        readinessProbe:
          exec:
            command:
            {{- range $value := .Values.deployment.readinessProbe.exec.command }}
            - {{ $value }}
            {{- end }}
        {{- end }}
        {{- if .Values.deployment.env }}
        env:
        {{- range $value := .Values.deployment.env }}
        - name: {{ $value.name }}
          value: {{ $value.value }}
        {{- end }}
        {{- end }}
        ports:
        - containerPort: {{ .Values.deployment.port }}
          name: {{ .Values.serviceName }}
      {{- if and (.Values.deployment.volumeMounts) (.Values.deployment.volumes) }}
        volumeMounts:
        {{- range $value := .Values.deployment.volumeMounts }}
        - name: {{ $value.name }}
          mountPath: {{ $value.mountPath }}
          subPath: {{ $value.subPath }}
        {{- end }}    
      restartPolicy: {{ .Values.deployment.restartPolicy | default  "Always"}}
      {{- if .Values.deployment.serviceAccountName }}
      serviceAccountName: {{ .Values.appName }}-{{ .Values.environment }} 
      {{- end }}               
      volumes:
        {{- range $value := .Values.deployment.volumes }}
        - name: {{ $value.name }}
        {{- if $value.secret }}
          secret:
            secretName: {{ $value.secret.secretName }}
        {{- else if $value.configMap }}
          configMap:
            name: {{ $value.configMap.name }}
        {{- else if $value.emptyDir }}
          emptyDir: {{ $value.emptyDir }}
        {{- else if $value.persistentVolumeClaim }}
          persistentVolumeClaim:
            claimName: {{ $value.persistentVolumeClaim.claimName }}
        {{- end }}   
        {{- end }}
      {{- end }}
---
{{- end }}