{{- if .Values.ingress }}
{{- range $value := .Values.ingress }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $value.name | default $.Values.serviceName }}
  namespace: {{ $.Values.namespace | lower }}
  annotations:
    {{- if $value.annotations }}
    {{- toYaml $value.annotations | nindent 4 }}
    {{- end }}
    {{- if and ( $value.tls ) ( $value.tls.enabled ) ( $value.tls.type ) }}
    {{- if and ( eq ($value.tls.enabled ) true  ) ( eq ($value.tls.type ) "auto" ) ( ne ($value.tls.enabled | toString ) "<nil>" )  }}
    cert-manager.io/cluster-issuer: {{ $.Values.clusterIssuer }}
    certmanager.k8s.io/acme-challenge-type: http01
    {{- end }}
    {{- if and ( eq ($value.tls.oauth_enabled ) true  ) ( ne ($value.tls.oauth_enabled | toString ) "<nil>" )  }}
    nginx.ingress.kubernetes.io/auth-signin: https://$host/oauth2/start?rd=$http_host$request_uri
    nginx.ingress.kubernetes.io/auth-url: https://$host/oauth2/auth  
    {{- end }}
 
    {{- end }}
    {{- if and ( eq ($value.tls.redirect) true ) ( ne ($value.tls.redirect | toString ) "<nil>" )  }}
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
    {{- end }}
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "Referrer-Policy: no-referrer";
      more_set_headers "X-Frame-Options: DENY";
      more_clear_headers "X-Powered-By";
    
spec:
  ingressClassName: nginx
  rules:
    - host: {{ $value.hostName | quote }}
      http:
        paths:
        {{- range  $value := $value.paths }}
          - path: {{ . }}
            pathType: Prefix
            backend:
              service:
                name: {{ default $.Values.service.name }}
                port:
                  number:  {{ $.Values.deployment.port }} 
        {{- end }}      
              
  {{- if and ( eq ($value.tls.enabled ) true  ) ( ne ($value.tls.enabled | toString ) "<nil>" )  }}
  {{- if or ( eq ($value.tls.type ) "auto"  )  ( eq ($value.tls.type ) "manual"  ) }}
  tls:
    - hosts:
        - {{ $value.hostName }}
      secretName: {{- if  $value.tls.secretName }} {{ $value.tls.secretName }} {{- else }} {{ $.Values.serviceName }}-crt-secret {{- end }}
  {{- end }}
  {{- end }}
---
{{- end }}
{{- end }}