{{- if .Values.secrets }}
{{- range $value := .Values.secrets }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $value.name }}
  namespace: {{ $.Values.namespace | lower }}
  {{- if $value.type }}
  template:
    type: {{ $value.type }}
  {{- end }}
spec:
  refreshInterval: {{ $value.refreshInterval | default "1m" }}             # rate SecretManager pulls GCPSM
  secretStoreRef:
    kind: {{ $value.secretStoreRef.kind | default "ClusterSecretStore" }}
    name: {{ $value.secretStoreRef.name | default "gcp-store" }}       # name of the SecretStore (or kind specified)
  target:
    name: {{ $.Values.serviceName }}-secret   # name of the k8s Secret to be created
    # creationPolicy: Owner
  data:
  {{- range $value := $value.data }}
  - secretKey: {{ $value.secretKey }}
    remoteRef:
      key: {{ $value.remoteRef.key }}
      {{- if $value.remoteRef.property }}
      property: {{ $value.remoteRef.property }}
      {{- end }}
  {{- end }}
---
{{- end }}
{{- end }}