{{- if .Values.service }}
kind: Service
apiVersion: v1
metadata:
  namespace: {{ .Values.namespace | lower }}
  name: {{ .Values.service.name }}
  labels:
    app: {{ .Values.serviceName }}
  {{- if .Values.service.labels }}
    {{- toYaml .Values.service.labels | nindent 4 }}
  {{- end }}
  {{- if .Values.service.annotations }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
  {{- end }}
spec:
  selector:
    app: {{ .Values.serviceName }}
  type: {{ .Values.service.type | default  "ClusterIP"}}
  ports:
  {{- range  $value := .Values.service.ports }}
    - protocol: {{ ($value.protocol) | default "TCP" }}
      name: {{ $.Values.serviceName }}
      port: {{ $value.port }}
      targetPort: {{ $value.port }}
  {{- end }}
---
{{- end }}