{{- if .Values.statefulSet }}
apiVersion: apps/v1
kind: statefulSet
metadata:
  name: {{ .Values.serviceName }}
  namespace: {{ .Values.namespace | lower }}
  labels:
    app: {{ .Values.serviceName }}
spec:
  replicas: {{ .Values.replicaCount | default  "1" }}
  selector:
    matchLabels:
      app: {{ .Values.serviceName }}
  template:
    metadata:
      labels:
        app: {{ .Values.serviceName }}
    spec:
      {{- if .Values.statefulSet.tolerations }}
      tolerations:
      {{- range $value := .Values.statefulSet.tolerations }}
      - key: {{ $value.key }}
        operator: {{ $value.operator }}
        value: {{ $value.value }}
        effect: {{ $value.effect }}
      {{- end }}
      {{- end }}
      {{- if .Values.statefulSet.nodeSelector }}
      nodeSelector:
        type: {{ .Values.statefulSet.nodeSelector.type }}
      {{- end }}
      containers:
      - image: {{ .Values.statefulSet.image }}:{{ .Values.statefulSet.tag }}
        imagePullPolicy: {{ .Values.statefulSet.pullPolicy | default  "Always"}}
        name: {{ .Values.serviceName }}
        {{- if .Values.statefulSet.command }}
        command: {{ .Values.statefulSet.command }}
        {{- end }}
        {{- if .Values.statefulSet.args }}
        args: {{ .Values.statefulSet.args }}
        {{- end }}
        {{- if .Values.statefulSet.startupProbe }}
        startupProbe:
          exec:
            command:
            {{- range $value := .Values.statefulSet.startupProbe.exec.command }}
            - {{ $value }}
            {{- end }}
          initialDelaySeconds: 30
        {{- end }}
        {{- if .Values.statefulSet.livenessProbe }}
        readinessProbe:
          exec:
            command:
            {{- range $value := .Values.statefulSet.livenessProbe.exec.command }}
            - {{ $value }}
            {{- end }}
        {{- end }}
        {{- if .Values.statefulSet.env }}
        env:
        {{- range $value := .Values.statefulSet.env }}
        - name: {{ $value.name }}
          value: {{ $value.value }}
        {{- end }}
        {{- end }}
        ports:
        - containerPort: {{ .Values.statefulSet.port }}
          name: {{ .Values.serviceName }}
        volumeMounts:
        {{- range $value := .Values.statefulSet.volumeMounts }}
        - name: {{ $value.name }}
          mountPath: {{ $value.mountPath }}
          subPath: {{ $value.subPath }}
        {{- end }}    
      restartPolicy: {{ .Values.statefulSet.restartPolicy | default  "Always"}}
      serviceAccountName: {{ .Values.appName }}-{{ .Values.environment }}                
      volumes:
        {{- range $value := .Values.statefulSet.volumes }}
        - name: {{ $value.name }}
        {{- if $value.secret }}
          secret:
            secretName: {{ $value.secret.secretName }}
        {{- else if $value.configMap }}
          configMap:
            name: {{ $value.configMap.name }}
        {{- else if $value.emptyDir }}
          emptyDir: {{ $value.emptyDir }}
        {{- else if $value.persistentVolumeClaim }}
          persistentVolumeClaim:
            claimName: {{ $value.persistentVolumeClaim.claimName }}
        {{- end }}   
        {{- end }}
---
{{- end }}